version: '3'

services:
  #userDatabase:
   # image: mysql
    #environment:
     # - MYSQL_ROOT_PASSWORD=root
    #ports:
     # - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
  shopDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
