"""Removed available products

Revision ID: f1e8d97f60e5
Revises: 85ad6a2d1515
Create Date: 2023-09-03 03:03:47.199253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1e8d97f60e5'
down_revision = '85ad6a2d1515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('available_products')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_products', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
